name: DartPolymerCodelab
description: A sample Polymer application
dependencies:
    polymer: any
    core_elements: ">=0.2.2+1 <0.3.0"
    paper_elements: ">=0.3.0+1 <0.4.0"
transformers:
- polymer:
    entry_points: web/dartpolymercodelab.html
